name: Microservices CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # -------------------- VOTE SERVICE --------------------
  vote-service:
    name: Vote Service CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Lint Vote Service (Flake8)
        run: |
          pip install flake8
          flake8 vote/app.py

      - name: Run SAST on Vote Service (Bandit)
        run: |
          pip install bandit
          bandit -r vote/ -ll -f json -o bandit-results.json || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Vote service image
        uses: docker/build-push-action@v5
        with:
          context: ./vote
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/result-find-your-bias:${{ github.sha }}

  # -------------------- RESULT SERVICE --------------------
  result-service:
    name: Result Service CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Node dependencies
        run: |
          cd result
          npm install

      - name: Run Prettier check
        run: |
          npm install prettier
          npx prettier --check "server.js"
        working-directory: result

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Result service image
        uses: docker/build-push-action@v5
        with:
          context: ./result
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/result-find-your-bias:${{ github.sha }}

  # -------------------- WORKER SERVICE --------------------
  worker-service:
    name: Worker Service CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Worker service image
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          push: true
